repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1  # add version here
    hooks:
      - id: poetry-check
        args: ["-C", "./backend"]
      - id: poetry-lock
        args: ["-C", "./backend"]