repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1  # add version here
    hooks:
      - id: poetry-check
        args: ["-C", "./backend"]
      - id: poetry-lock
        args: ["-C", "./backend"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        files: '^backend/.*\.py$'
        language: system
        types: [python]
        args:
          [
            "--disable=E0401,R0913,E1129,W0621,W0105",
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]