version: '3.5'

volumes:
  quick-parking-data:

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile.app
      args:
        - APP_USER=${APP_USER}
    container_name: ${APP_HOST}
    ports:
      - ${PROD_PORT}:${PROD_PORT}
    environment:
      - PROD_PORT=${PROD_PORT}
      - DB_CONNECT=${DB_CONNECT}
    networks:
      - quick-parking-network
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: ${DB_HOST}
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - quick-parking-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    networks:
      - quick-parking-network

networks:
  quick-parking-network:
    driver: bridge
