name: Backend

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install -C backend/
    - name: Analysing the code with pylint
      working-directory: ./backend
      run: |
        poetry run pylint --disable=E0401,R0913,E1129,W0621,W0105,R0801,R0904 -rn -sn $(git ls-files '*.py')
    - name: Run pytest
      working-directory: ./backend
      run: |
        poetry run python -m pytest