name: ESLint

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          package_json_file: frontend/package.json
      - name: Install dependencies
        working-directory: frontend
        run: pnpm install
      - name: Run ESLint
        working-directory: frontend
        run: pnpm lint
