name: ESLint

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        working-directory: frontend
        run: pnpm install
      - uses: pnpm/action-setup@v2
      - name: Run ESLint
        working-directory: frontend
        run: pnpm lint
